src/rtp/02_api_service_provider.tf
src/rtp/99_variables.tf
src/rtp/api/pagopa/send_policy.xml
src/rtp/env/dev/terraform.tfvars
src/rtp/env/prod/terraform.tfvars
src/rtp/env/uat/terraform.tfvars

This PR proposes to add a condition in the send RTP policy. A boolean flag controls the inclusion of the authentication fragment.
- add variable to control authentication
- add variable check before including fragment
With this change we can test RTP send through web page.
Target: 
```
```
---

feat: [SRTP-156] Add a variable to enable auth on send API

---

src/rtp/env/dev/terraform.tfvars
src/rtp/env/uat/terraform.tfvars

This PR reverts a temporary change that disabled authentication on send RTP API.
- change feature flag
Target: 
```
```
---

feat: [SRTP-187] re-enable send RTP authentication

---

.github/workflows/validate-openapi.yaml
src/rtp/api/pagopa/activation.yaml
src/rtp/api/pagopa/send_policy.xml

This PR proposes to improve the restiness of `findByPayerId` into something more adherent to rest principles
Target: 
```
```
---

fix: [SRTP-192] improve findby uri restiness

---

src/rtp/api/pagopa/activation.yaml

This PR proposes to remove the page and size parameter from the payer endpoint
Target: 
```
```
---

fix: [SRTP-194] remove page and size from payer endpoint

---

src/rtp/api/pagopa/activation.yaml
src/rtp/api/pagopa/send.openapi.yaml

This PR proposes to update the openapi with the correct information about `servers`
Target: 
```
```
---

chore: [SRTP-199] fix servers info in openapi

---

src/rtp/api/pagopa/send.openapi.yaml

fix: [SRTP-20+6 update send api swagger

---

src/rtp/api/pagopa/send.openapi.yaml

fix: [SRTP-206] update send api swagger

---

src/rtp/02_api_service_provider.tf

feat: [SRTP-210] change from segment to header versioning strategy api

---

src/rtp/api/pagopa/send.openapi.yaml

fix: Add version on params for send openapi

---

src/rtp/02_api_mock.tf
src/rtp/api/pagopa/EPC133-22_v3.1_SRTP_spec.openapi.yaml
src/rtp/api/test/mock_policy_epc.xml

This PR proposes to add the EPC mock to expose the RTP send api
Target: 
```
```
---

feat: [SRTP-102] add mock epc

---

src/rtp/api/pagopa/activation.yaml

This PR proposes to replace the LEI regex with the VAT in order to allow registration of creditor service provider that are not PSP entity.
Target: 
```
```
---

fix: [SRTP-225] replace LEI with VAT pattern

---

README.md
src/rtp/api/pagopa/activation.yaml
src/rtp/api/pagopa/send.openapi.yaml

Align send and activation swagger to rtp-activatior swaggers.
Target: 
```
```
---

fix: [SRTP-248] Align swagger

---

src/rtp/api/pagopa/send.openapi.yaml

Since the versioning strategy was moved inside the header, we must remove the "v1" versioning inside the URI path.
Target: 
```
```
---

fix: [SRTP-241] delete versioning inside path uri

---

.spectral.yml
src/rtp/api/pagopa/activation.yaml
src/rtp/api/pagopa/takeover.yaml

Updated `.spectral.yml`: more rules added to verify OpenAPI descriptor.
Updated `activation.yaml`: takeover operation added and general review on error description.
New requirement.
Complexity reduction.
Target: 
```
```
---

breaking: Takeover [SRTP-256]

---

src/rtp/api/pagopa/payees_registry.yaml

feat: Payees registry OpenAPI specification.

---

src/rtp/02_api_send_callback.tf
src/rtp/02_api_service_provider.tf
src/rtp/api/pagopa/callback.openapi.yaml
src/rtp/api/pagopa/send_callback.openapi.yaml

This will expose the send-callback endpoint to receive callbacks from the send SRTP operation. 
It uses a dedicated Openapi swagger to set it up.
The dedicated swagger is useful for internal documentation and is an easy way to add another callback endpoint, but it is not strictly necessary.
All the components inside the swagger are from the EPC swagger, not all of them are necessary, but for convenience, I took them all. 
- Add `azurerm_api_management_api_version_set`
- Add `azurerm_api_management_api`
- Add `azurerm_api_management_product_api`
We want to receive callbacks from external services.
Target: 
```
```
---

feat: [SRTP-323] Add api config for callback

---

src/rtp/api/pagopa/send.openapi.yaml

feat: Added stuff to update a RTP [SRTP-337].

---

src/rtp/api/test/mock_policy_epc.xml

Fixed the Service Provider mock to return status code 201 in the happy path, as per specifications.
Updated mock_policy_epc to return status code 201.
The mock was returning an incorrect status code, causing inconsistencies. This fix ensures compliance with the expected behavior.
Target: 
```
```
---

fix: [STRP-362] fix status code on mock_policy_epc

---

src/rtp/02_apim_diagnostic.tf
src/rtp/99_locals.tf
src/rtp/99_variables.tf
src/rtp/env/dev/terraform.tfvars
src/rtp/env/prod/terraform.tfvars
src/rtp/env/uat/backend.tfvars
src/rtp/env/uat/terraform.tfvars

This PR proposes to enable API diagnostics for RTP APIs.
- create APIM diagnostic for each RTP API
- collect diagnostics with Application Insights
With this change we can correlate a request received by APIM to underlying stack (microservice and DB).
Target: 
```
-target=azurerm_api_management_api_diagnostic.rtp_apim_api_diagnostics
```
---

feat: [SRTP-408] Collect APIM diagnostics in Application Insights

---

src/rtp/api/pagopa/send.openapi.yaml

This PR introduces a new API operation within the rtp-apis OpenAPI specification. Specifically, it adds the GET /rtps/{rtpId} endpoint, which allows clients to retrieve a single RTP (Request to Pay) resource by its unique identifier.
- Added a new GET /rtps/{rtpId} endpoint to the OpenAPI specification in the rtp-apis definition.
- Introduced a new schema Rtp representing the structure of the RTP entity returned by the endpoint.
- Added supporting schemas: Event, RtpStatus, and RtpEvent.
This change adds a GET /rtps/{rtpId} endpoint to allow retrieval of RTP data by ID. It enables client systems to access detailed RTP information, including status and event history, useful for monitoring or integration needs. 
Target: 
```
```
[Link to test …

feat: [SRTP-564] add new endpoint to retrieve RTP details by ID
